In [2]:
import numpy as np

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [8]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [9]:
A.dot(B)

NameError: name 'A' is not defined

In [10]:
a=np.array([3.3,4.5,1.2,5.7,0.3])
a.sum()

np.float64(15.0)

In [11]:
a.min()

np.float64(0.3)

In [12]:
a.max()

np.float64(5.7)

In [ ]:
a.mean()

np.float64(3.0)