Splitting array

In [ ]:
import numpy as np
a= np.arange(10)
print('First Array')
print(a)
print('\n')
print('splitting the array in 2 equal size arrays.')
b=np.split(a,2)
print(b)
print('\n')

First Array
[0 1 2 3 4 5 6 7 8 9]


splitting the array in 2 equal size arrays.
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]




In [ ]:
a=np.arange(10)
#splitting the array indicated first at 3,second 5 remaining in 3rd
print('splitting the array indicated first at 3,second 5 and remaining in 3rd.')
c=np.split(a,[3,5,9])
print(c)
print('\n')

splitting the array indicated first at 3,second 5 and remaining in 3rd.
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([9])]




In [15]:
a=np.arange(9)
#splitting the array indicated first at 4,second 5-7 remaining in 3rd
print('splitting the array indicated first at 3,second 5 and remaining in 3rd.')
c=np.split(a,[2,3,5])
print(c)
print('\n')

splitting the array indicated first at 3,second 5 and remaining in 3rd.
[array([0, 1]), array([2]), array([3, 4]), array([5, 6, 7, 8])]




In [14]:
import numpy as np
a=np.arange(12).reshape(4,3)
a
#np.split(a,4)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

data type for ndarray

In [16]:
array=np.array([3,4,5],dtype=float)

In [17]:
array=np.array([3,4,5],dtype=np.float64)

In [18]:
array

array([3., 4., 5.])

In [19]:
array.dtype

dtype('float64')

In [21]:
array1=np.array([3,4,5,6,5.5],dtype = np.int32)

In [23]:
import numpy as np
array1=np.array([1,2,3,4,5])
array.dtype

dtype('float64')

In [24]:
array1.astype(np.float64)

array([1., 2., 3., 4., 5.])

If the Float is casted into it.

In [25]:
array2=np.array([1.2,4.5,6.7,4.0])
array2.astype(np.int32)

array([1, 4, 6, 4], dtype=int32)

In [29]:
array1 =np.array(['3.4','5.6','5.5'],dtype = np.bytes_)#np.strings

In [30]:
array1.dtype

dtype('S3')

In [31]:
array1

array([b'3.4', b'5.6', b'5.5'], dtype='|S3')

In [32]:
array1.astype(np.float64)

array([3.4, 5.6, 5.5])

In [34]:
alist=[1,2,3,4,5]
list2=[6,7,8,9,10]
alist=list2

In [36]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
(arr*0.005)

array([[0.005, 0.01 , 0.015],
       [0.02 , 0.025, 0.03 ]])

In [40]:
%time arr**2

CPU times: total: 0 ns
Wall time: 80.6 μs


array([[ 1,  4,  9],
       [16, 25, 36]])

comparision of array

In [41]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6]])