**Broadcasting Basics**

113. Write a program to apply broadcasting between a 2D and 1D array
• Use broadcasting to apply operations on arrays of different shapes.
• Understand NumPy's broadcasting rules (same or size-1 dimensions).
• Predict result shapes after operations like A + b.

In [1]:
import numpy as np

In [8]:
A = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([10, 20, 30])

result = A + b

print("A shape:", A.shape)
print("b shape:", b.shape)
print("Result:" )
print(result)
print("Result shape:", result.shape)

A shape: (2, 3)
b shape: (3,)
Result:
[[11 22 33]
 [14 25 36]]
Result shape: (2, 3)


114. Write a program to broadcast a 1D row vector across a 2D matrix
• Understand how NumPy expands smaller arrays to match larger ones.
• Practice horizontal/vertical broadcasting operations.
• Apply broadcasting rules to addition, multiplication, etc.

In [9]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])

row = np.array([10, 20, 30])

addition = matrix + row
multiplication = matrix * row

print("Addition:")
print(addition)

print("Multiplication:")
print(multiplication)

Addition:
[[11 22 33]
 [14 25 36]]
Multiplication:
[[ 10  40  90]
 [ 40 100 180]]


**Advanced Broadcasting with Higher Dimensions**

115. Write a program to multiply two 3D arrays using complex broadcasting
• Reshape arrays to (3,1,2) and (3,2,1) and apply broadcasting.
• Understand compatibility conditions for higher-dimensional arrays.
• Visualize resulting 3D array after broadcasting multiplication.

In [ ]:
A = np.arange(6).reshape(3, 1, 2)
B = np.arange(6).reshape(3, 2, 1)

result = A * B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("Result shape:", result)
print("Result:")
print(result)

A shape: (3, 1, 2)
B shape: (3, 2, 1)
Result shape: (3, 2, 2)
Result:
[[[ 0  0]
  [ 0  1]]

 [[ 4  6]
  [ 6  9]]

 [[16 20]
  [20 25]]]


116. Write a program to verify broadcasting compatibility rules for mismatched
shapes
• Apply Rule 1: Insert 1 in missing dimensions.
• Apply Rule 2: Replicate along dimensions of size 1.
• Test and resolve shape mismatch errors in real use cases.

In [11]:
A = np.ones((2, 3))
B = np.ones((3,))

try:
    result = A + B
    print("Compatible")
    print("Result shape:", result.shape)
except ValueError:
    print("Not compatible")

# Mismatched example
C = np.ones((2, 3))
D = np.ones((2,))

try:
    result = C + D
    print("Compatible")
    print("Result shape:", result.shape)
except ValueError:
    print("Not compatible: Shape mismatch")

Compatible
Result shape: (2, 3)
Not compatible: Shape mismatch


**Creating Series from Various Sources**

117. Write a program to create a Series from a list with and without custom index
• Create a basic Series using a list of numeric values.
• Apply custom labels as index instead of default integer index.
• Interpret the string representation of a Series.

In [13]:
import pandas as pd

data = [10, 20, 30, 40]

# Without custom index
s1 = pd.Series(data)

# With custom index
s2 = pd.Series(data, index=['A', 'B', 'C', 'D'])

print("Series without custom index:")
print(s1)

print("\nSeries with custom index:")
print(s2)

Series without custom index:
0    10
1    20
2    30
3    40
dtype: int64

Series with custom index:
A    10
B    20
C    30
D    40
dtype: int64


118. Write a program to create a Series from a NumPy array and verify data linkage
• Convert a NumPy array into a pandas Series.
• Observe dynamic linking between original array and Series.
• Understand mutability and reference behavior.

In [23]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30, 40])

s = pd.Series(arr, copy=False)

print("Original NumPy array:")
print(arr)

print("\nOriginal Series:")
print(s)

arr[0] = 100

print("\nAfter changing NumPy array:")
print(arr)

print("\nSeries after changing NumPy array:")
print(s)

Original NumPy array:
[10 20 30 40]

Original Series:
0    10
1    20
2    30
3    40
dtype: int64

After changing NumPy array:
[100  20  30  40]

Series after changing NumPy array:
0    100
1     20
2     30
3     40
dtype: int64


119. Write a program to create a Series from a dictionary with custom index
• Use dictionary key-value pairs to form Series index and data.
• Handle missing keys using an index list (introducing NaN).
• Understand auto-alignment of labels and handling of missing data.

In [27]:
import pandas as pd

data = {
    'Laptop': 50000,
    'Desktop': 20000,
    'Tablet': 30000,
    'Smartphone': 40000
}

s = pd.Series(data, index=['Laptop', 'Desktop', 'Tablet', 'Smartphone'])  

print(s)

Laptop        50000
Desktop       20000
Tablet        30000
Smartphone    40000
dtype: int64


**Indexing and Value Access**

120. Write a program to access Series values using position and label indexing
• Use integer-based and label-based indexing.
• Slice Series using : notation and label lists.
• Compare Series indexing with NumPy array slicing.

In [3]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

print("Series:")
print(s)

print("\nPosition indexing:")
print(s.iloc[1])

print("\nLabel indexing:")
print(s.loc['C'])

print("\nPosition slicing:")
print(s.iloc[1:3])

print("\nLabel slicing:")
print(s.loc['B':'C'])

print("\nSelected labels:")
print(s.loc[['A', 'D']])

Series:
A    10
B    20
C    30
D    40
dtype: int64

Position indexing:
20

Label indexing:
30

Position slicing:
B    20
C    30
dtype: int64

Label slicing:
B    20
C    30
dtype: int64

Selected labels:
A    10
D    40
dtype: int64


121. Write a program to assign new values to Series elements using labels and indices
• Update values by direct index reference.
• Modify elements using label-based assignment.
• Explore partial updates on slices or selected labels.

In [4]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

s.iloc[1] = 25
s.loc['C'] = 35

print("Updated Series:")
print(s)

s.loc[['A', 'D']] = [15, 45]

print("\nAfter partial update:")
print(s)

Updated Series:
A    10
B    25
C    35
D    40
dtype: int64

After partial update:
A    15
B    25
C    35
D    45
dtype: int64


**Mathematical and Conditional Operations**

122. Write a program to filter Series values using a conditional expression
• Apply conditional filtering like series > 8.
• Extract matching entries using Boolean indexing.
• Chain logical conditions for multi-criteria filtering.

In [5]:
import pandas as pd

s = pd.Series([5, 10, 65, 20, 25])

result = s[s > 8]

print("Values greater than 8:")
print(result)

Values greater than 8:
1    10
2    65
3    20
4    25
dtype: int64


123. Write a program to apply arithmetic and mathematical functions on Series
• Perform element-wise arithmetic like series / 2.
• Use NumPy ufuncs such as np.log() on Series.
• Interpret return types and shape preservation.

In [6]:
import pandas as pd
import numpy as np

s = pd.Series([10, 20, 30, 40])

print("Original Series:")
print(s)

print("\nAfter division by 2:")
print(s / 2)

print("\nLogarithm:")
print(np.log(s))

Original Series:
0    10
1    20
2    30
3    40
dtype: int64

After division by 2:
0     5.0
1    10.0
2    15.0
3    20.0
dtype: float64

Logarithm:
0    2.302585
1    2.995732
2    3.401197
3    3.688879
dtype: float64


**Evaluating and Counting Series Data**

124. Write a program to check for duplicate, unique, and value counts in a Series
• Use unique() to get distinct values.
• Use value_counts() to summarize frequency.
• Compare distribution of repeated and unique values.

In [7]:
import pandas as pd

s = pd.Series([10, 20, 10, 30, 20, 10])

print("Unique values:")
print(s.unique())

print("\nValue counts:")
print(s.value_counts())

print("\nDuplicate values:")
print(s[s.duplicated()])

Unique values:
[10 20 30]

Value counts:
10    3
20    2
30    1
Name: count, dtype: int64

Duplicate values:
2    10
4    20
5    10
dtype: int64


125. Write a program to evaluate element membership using isin() function
• Test which values are present in a Series.
• Use the result to extract matching elements.
• Combine isin() with logical indexing for filtering.

In [8]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50])

result = s.isin([20, 40])

print("Membership result:")
print(result)

print("\nMatching elements:")
print(s[result])

Membership result:
0    False
1     True
2    False
3     True
4    False
dtype: bool

Matching elements:
1    20
3    40
dtype: int64


**Handling Missing Data (NaNs)**

126. Write a program to create a Series with NaN values and detect them
• Insert np.NaN in a Series manually.
• Identify missing values using isnull() and notnull().
• Practice recognizing and printing incomplete records.

In [14]:
import pandas as pd
import numpy as np

sales = pd.Series([10, np.nan, 30, np.nan, 50])

# Unique values
print("Unique sales quantities:")
print(sales.unique())

# null values
print("\nNull values in sales data:")
print(sales.isnull())

# total number of null values
print("\nTotal number of null values:")
print(sales.isnull().sum())

# not null values
print("\nNot null values in sales data:")
print(sales.notnull().sum())

Unique sales quantities:
[10. nan 30. 50.]

Null values in sales data:
0    False
1     True
2    False
3     True
4    False
dtype: bool

Total number of null values:
2

Not null values in sales data:
3


127. Write a program to filter valid and missing values using Boolean masks
• Use notnull() to select valid entries.
• Use isnull() to isolate missing entries.
• Understand how these tools are useful for data cleaning.

In [15]:
import pandas as pd
import numpy as np

sales = pd.Series([10, np.nan, 30, np.nan, 50])

# Filter valid values
print("Valid sales values:")
print(sales[sales.notnull()])

# Filter missing values
print("\nMissing sales values:")
print(sales[sales.isnull()])

Valid sales values:
0    10.0
2    30.0
4    50.0
dtype: float64

Missing sales values:
1   NaN
3   NaN
dtype: float64


Extra example

In [55]:
import numpy as np
import pandas as pd

# Create NumPy array
marks = np.array([75, 82, 68, 91, 88])

# Create Series from NumPy array
series = pd.Series(marks)

print("Original Series:")
print(series)

# Modify the NumPy array
marks[2] = 95

print("\nNumPy array after modification:")
print(marks)

print("\nSeries after modifying NumPy array:")
print(series)

Original Series:
0    75
1    82
2    68
3    91
4    88
dtype: int64

NumPy array after modification:
[75 82 95 91 88]

Series after modifying NumPy array:
0    75
1    82
2    68
3    91
4    88
dtype: int64


In [26]:
import pandas as pd
marks = np.array([75, 85, 90, 95, 80])
series = pd.Series(marks, index=['Math', 'Science', 'English', 'History', 'Art'])
print(series)

Math       75
Science    85
English    90
History    95
Art        80
dtype: int64


In [30]:
import pandas as pd
marks = pd.Series([75, 85, 90, 95, 80],
                  index=['Niyati', 'Aarav', 'Riya', 'Kabir', 'Anaya'])

print("Original Series:")
print(marks)

print("\nMarks of Niyati:", marks['Niyati'])
print("\nMarks of 3rd student:", marks.iloc[2])
print("\nMarks of First three students:", marks.iloc[:3])
print("\nMarks of Aarav and Kabir :",marks[['Aarav', 'Kabir']])

Original Series:
Niyati    75
Aarav     85
Riya      90
Kabir     95
Anaya     80
dtype: int64

Marks of Niyati: 75

Marks of 3rd student: 90

Marks of First three students: Niyati    75
Aarav     85
Riya      90
dtype: int64

Marks of Aarav and Kabir : Aarav    85
Kabir    95
dtype: int64


In [56]:
import pandas as pd

sales = {
    'Laptop': 55000,
    'Mobile': 25000,
    'Tablet': 18000
}

# Create Series from dictionary
series1 = pd.Series(sales)

print("Original Series:")
print(series1)

# Create Series with custom index
index = ['Mobile', 'Headphone', 'Laptop', 'Tablet']
series2 = pd.Series(sales, index=index)

print("\nSeries with custom index:")
print(series2)

Original Series:
Laptop    55000
Mobile    25000
Tablet    18000
dtype: int64

Series with custom index:
Mobile       25000.0
Headphone        NaN
Laptop       55000.0
Tablet       18000.0
dtype: float64


In [38]:
import pandas as pd
stock = pd.Series([50000, 20000, 30000, 40000],
                  index=['Laptop', 'Desktop', 'Tablet', 'Smartphone'])

print("Original stock")
print(stock)

stock['Laptop'] = 55000
stock.iloc[1] = 25000

stock[['Tablet', 'Smartphone']] = stock[['Tablet', 'Smartphone']] + 1000

print("\nUpdated stock")
print(stock)

Original stock
Laptop        50000
Desktop       20000
Tablet        30000
Smartphone    40000
dtype: int64

Updated stock
Laptop        55000
Desktop       25000
Tablet        31000
Smartphone    41000
dtype: int64


In [43]:
import pandas as pd
scores = pd.Series([75, 85, 90, 95, 80 , 65 , 84 ],
                   index=['Niyati', 'Nisha', 'Mira', 'Krina', 'Mahi', 'Diya', 'Aesha'])

print("Scores greater than 80:")
print(scores[scores > 80])

print("Scores between 60 and 80:")
print(scores[(scores >= 60) & (scores <= 85)])

print("Scores between 70 and 90 :")
print(scores[(scores >= 70) & (scores <= 90)])

Scores greater than 80:
Nisha    85
Mira     90
Krina    95
Aesha    84
dtype: int64
Scores between 60 and 80:
Niyati    75
Nisha     85
Mahi      80
Diya      65
Aesha     84
dtype: int64
Scores between 70 and 90 :
Niyati    75
Nisha     85
Mira      90
Mahi      80
Aesha     84
dtype: int64


In [1]:
import pandas as pd
import numpy as np

sales = pd.Series([12,45,78,96,78,56,64],
                    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

print("Orriginal Sales Data : ")
print(sales)

print("Sales After adding 5 :")
print(sales + 5)

print("Sales After dividing by 2 :")
print(sales / 2)

print("Sales root square :")
print(np.sqrt(sales))

Orriginal Sales Data : 
Mon    12
Tue    45
Wed    78
Thu    96
Fri    78
Sat    56
Sun    64
dtype: int64
Sales After adding 5 :
Mon     17
Tue     50
Wed     83
Thu    101
Fri     83
Sat     61
Sun     69
dtype: int64
Sales After dividing by 2 :
Mon     6.0
Tue    22.5
Wed    39.0
Thu    48.0
Fri    39.0
Sat    28.0
Sun    32.0
dtype: float64
Sales root square :
Mon    3.464102
Tue    6.708204
Wed    8.831761
Thu    9.797959
Fri    8.831761
Sat    7.483315
Sun    8.000000
dtype: float64


In [49]:
import pandas as pd
sales = pd.Series([12,45,78,96,78,56,64])

print("Unique Sales quantities :")
print(sales.unique())

print("Frequency of each sales quantity :")
print(sales.value_counts())

print("Most frequently occurring sales quantity :")
print(sales.value_counts().idxmax())

Unique Sales quantities :
[12 45 78 96 56 64]
Frequency of each sales quantity :
78    2
12    1
45    1
96    1
56    1
64    1
Name: count, dtype: int64
Most frequently occurring sales quantity :
78


In [52]:
import pandas as pd
departments = pd.Series(['AIML', 'CSE', 'IT', 'CE', 'ME', 'EC', 'EE'],
                        index=['Nirav','Neha','Nikita','Kavya','Anvi','Mira','Krina'])

required_departments = ['AIML', 'CSE', 'IT','EC']

mask = departments.isin(required_departments)

print("Boolean Mask for selected departments:")
print(mask)

print("Employees in selected departments:")
print(departments[mask])

Boolean Mask for selected departments:
Nirav      True
Neha       True
Nikita     True
Kavya     False
Anvi      False
Mira       True
Krina     False
dtype: bool
Employees in selected departments:
Nirav     AIML
Neha       CSE
Nikita      IT
Mira        EC
dtype: str


In [53]:
import pandas as pd

sales = pd.Series([12,45,np.nan,78,96,78,np.nan,64])

print("Unique Sales quantities :")
print(sales.unique())

print("Null values in the sales data :")
print(sales.isnull().sum()) 



Unique Sales quantities :
[12. 45. nan 78. 96. 64.]
Null values in the sales data :
2
