Splitting array

In [ ]:
import numpy as np
a= np.arange(10)
print('First Array')
print(a)
print('\n')
print('splitting the array in 2 equal size arrays.')
b=np.split(a,2)
print(b)
print('\n')

First Array
[0 1 2 3 4 5 6 7 8 9]


splitting the array in 2 equal size arrays.
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]




In [ ]:
a=np.arange(10)
#splitting the array indicated first at 3,second 5 remaining in 3rd
print('splitting the array indicated first at 3,second 5 and remaining in 3rd.')
c=np.split(a,[3,5,9])
print(c)
print('\n')

splitting the array indicated first at 3,second 5 and remaining in 3rd.
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([9])]




In [15]:
a=np.arange(9)
#splitting the array indicated first at 4,second 5-7 remaining in 3rd
print('splitting the array indicated first at 3,second 5 and remaining in 3rd.')
c=np.split(a,[2,3,5])
print(c)
print('\n')

splitting the array indicated first at 3,second 5 and remaining in 3rd.
[array([0, 1]), array([2]), array([3, 4]), array([5, 6, 7, 8])]




In [14]:
import numpy as np
a=np.arange(12).reshape(4,3)
a
#np.split(a,4)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

data type for ndarray

In [16]:
array=np.array([3,4,5],dtype=float)

In [17]:
array=np.array([3,4,5],dtype=np.float64)

In [18]:
array

array([3., 4., 5.])

In [19]:
array.dtype

dtype('float64')

In [21]:
array1=np.array([3,4,5,6,5.5],dtype = np.int32)

In [23]:
import numpy as np
array1=np.array([1,2,3,4,5])
array.dtype

dtype('float64')

In [24]:
array1.astype(np.float64)

array([1., 2., 3., 4., 5.])

If the Float is casted into it.

In [25]:
array2=np.array([1.2,4.5,6.7,4.0])
array2.astype(np.int32)

array([1, 4, 6, 4], dtype=int32)

In [29]:
array1 =np.array(['3.4','5.6','5.5'],dtype = np.bytes_)#np.strings

In [30]:
array1.dtype

dtype('S3')

In [31]:
array1

array([b'3.4', b'5.6', b'5.5'], dtype='|S3')

In [32]:
array1.astype(np.float64)

array([3.4, 5.6, 5.5])

In [34]:
alist=[1,2,3,4,5]
list2=[6,7,8,9,10]
alist=list2

In [36]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
(arr*0.005)

array([[0.005, 0.01 , 0.015],
       [0.02 , 0.025, 0.03 ]])

In [40]:
%time arr**2

CPU times: total: 0 ns
Wall time: 80.6 μs


array([[ 1,  4,  9],
       [16, 25, 36]])

comparision of array

In [41]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr2>arr

array([[False, False, False],
       [False, False, False]])

In [44]:
arr2<arr

array([[False, False, False],
       [False, False, False]])

In [45]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [46]:
arr[0]

np.int64(10)

In [47]:
arr[-3]

np.int64(30)

In [48]:
arr[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [49]:
arr[-1]

np.int64(50)

In [51]:
arr[-2]

np.int64(40)

In [54]:
arr2d=np.arange(1,21).reshape(5,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
arr2d[1:-1,1:-1]
#arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [58]:
#slice this array[[10,11,12],[14,15,16],[18,19,20]] from above "arr2d".
arr2d[2:,1:]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [77]:
#arr3=[[1,3],[9,11],[17,19]]
arr3[0:3:1]

[[1, 3], [9, 11], [17, 19]]

In [81]:
#arr3=[[1,3],[9,11],[17,19]]
arr2d[::2,::2]

array([[ 1,  3],
       [ 9, 11],
       [17, 19]])

In [82]:
arr1 =np.array([12,13,14,15,16])
arr1

array([12, 13, 14, 15, 16])

In [84]:
arr1[3:5]

array([15, 16])

In [85]:
arr1[3:5]=20
arr1[3:5]

array([20, 20])

In [86]:
arr1

array([12, 13, 14, 20, 20])

In [87]:
arr2d=np.array([[10,20,30],[40,50,60],[30,50,70],[30,20,10],[80,70,45]])
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [30, 50, 70],
       [30, 20, 10],
       [80, 70, 45]])

In [88]:
arr2d[:2,2:]

array([[30],
       [60]])

In [89]:
arr2d[4:,:2]

array([[80, 70]])

In [90]:
arr2d[1:,2:3]

array([[60],
       [70],
       [10],
       [45]])

Assignment 84

In [91]:
import numpy as np

a = np.array([88,89,56,23,31])

print("Addition:", a + 2)
print("Subtraction:", a - 2)
print("Multiplication:", a * 2)
print("Division:", a / 2)

Addition: [90 91 58 25 33]
Subtraction: [86 87 54 21 29]
Multiplication: [176 178 112  46  62]
Division: [44.  44.5 28.  11.5 15.5]


Assignment 85

In [92]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


Assignment 86

In [93]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print("Addition:\n", a + b)
print("Multiplication:\n", a * b)

Addition:
 [[11 22 33]
 [14 25 36]]
Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]


Assignment 87

In [94]:
import numpy as np

a = np.array([1, 4, 9])

print("Original:", a)
print("Sin:", np.sin(a))
print("Square Root:", np.sqrt(a))
print("Log:", np.log(a))

Original: [1 4 9]
Sin: [ 0.84147098 -0.7568025   0.41211849]
Square Root: [1. 2. 3.]
Log: [0.         1.38629436 2.19722458]


Assignment 88

In [95]:
import numpy as np

a = np.array([1, 2, 3, 4])

result = a * np.sin(a)

print("Array:", a)
print("Result:", result)

Array: [1 2 3 4]
Result: [ 0.84147098  1.81859485  0.42336002 -3.02720998]
