In [1]:
import numpy as np
arr=np.array([0,1,2,3,4])
arr

array([0, 1, 2, 3, 4])

In [2]:
a=range(0,20)
print(type(a))
list(a)

<class 'range'>


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [74]:
import numpy as np
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
import numpy as np
an_arr=np.arange(20)
print(type(an_arr))
an_arr

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
import numpy as np
an_arr=np.arange(1000) #array
a_list=list(range(1000))#list
#show squares of all numbers
#a_list


In [7]:
%time for x in range(100000):an_arr2=an_arr**2


CPU times: total: 78.1 ms
Wall time: 91.9 ms


In [8]:
#an_arr2

In [12]:
%time for i in range(100000):a_list2=[x**2  for x in a_list]

CPU times: total: 3.67 s
Wall time: 3.82 s


In [17]:
list=[2,4,7,78]
list*5

[2, 4, 7, 78, 2, 4, 7, 78, 2, 4, 7, 78, 2, 4, 7, 78, 2, 4, 7, 78]

In [18]:
list+list

[2, 4, 7, 78, 2, 4, 7, 78]

In [19]:
a=np.array(list)
a*5

array([ 10,  20,  35, 390])

In [75]:
em=[]
list1=[2,3,5,6,7]
for i in list1:#print(i**2)
        j=i**2
        em.append(j)
print(em)

[4, 9, 25, 36, 49]


In [21]:
import numpy as np
list=[2,3,4,5,6]
arr=np.array(list)
#arr.dtype=np.int16
print(arr.itemsize)
print(arr.size)
print(arr.dtype)
print(arr)

8
5
int64
[2 3 4 5 6]


In [81]:
import numpy as np
list=[2,3,4,5,6]
arr=np.array(list)
#arr.dtype=np.int16
print(arr.itemsize)
print(arr.size)
print(arr.dtype)
print(arr)
arr.dtype=np.int16
print(arr.itemsize)
print(arr.size)
print(arr.dtype)
print(arr)


8
5
int64
[2 3 4 5 6]
2
20
int16
[2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 6 0 0 0]


C:\Users\Krina\AppData\Local\Temp\ipykernel_23176\1927854640.py:9: DeprecationWarning: Setting the dtype on a NumPy array has been deprecated in NumPy 2.5.
Instead of changing the dtype on an array x, create a new array with x.view(new_dtype)
  arr.dtype=np.int16


In [82]:
arr=np.arange(20)
arr.dtype

dtype('int64')

In [83]:
import numpy as np
list=[2,3,5,6,7]
arr1=np.array(list)

arr1.dtype=np.int16
arr1

C:\Users\Krina\AppData\Local\Temp\ipykernel_23176\3275164063.py:5: DeprecationWarning: Setting the dtype on a NumPy array has been deprecated in NumPy 2.5.
Instead of changing the dtype on an array x, create a new array with x.view(new_dtype)
  arr1.dtype=np.int16


array([2, 0, 0, 0, 3, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0],
      dtype=int16)

In [84]:
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [86]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [87]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
arr*5


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [89]:
import numpy as np
data = np.random.randn(3,3)
data


array([[-2.12279291, -0.0559835 ,  1.67595032],
       [ 0.49693856,  0.73571015,  0.26890022],
       [ 0.39808403,  1.67979034, -0.36975565]])

In [90]:
np.random.randn(2,3,2)

array([[[-1.07337765,  0.74071993],
        [ 0.12652777,  1.41698957],
        [ 0.38628712, -0.4368366 ]],

       [[-1.62743607, -0.69436577],
        [-0.84964991, -0.65169941],
        [-0.23665447,  0.36827332]]])

In [91]:
a = np.array([[0,1,2],[4,5,6]])
a

array([[0, 1, 2],
       [4, 5, 6]])

In [92]:
a = np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [93]:
np.random.randint(0,3)

0

In [94]:
np.random.randint(1,9)

4

In [ ]:
data=np.zeros((3,2))
data

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
data.shape

(3, 2)

In [ ]:
data.dtype
type(data)
#only type(data)  can print same output

numpy.ndarray

In [99]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data1=[6,7,8,9]
array1=np.array(data1)
print(array1)
array1.ndim

[6 7 8 9]


1

In [100]:
array1.dtype

dtype('int64')

In [ ]:
a=10
k=np.array(a)
print(k)
np.array(a).ndim

10


0

In [101]:
data2 = (6, 7.5, 8, 5, 8)
arr2=np.array(data2)
arr2

array([6. , 7.5, 8. , 5. , 8. ])

In [102]:
type(arr2)

numpy.ndarray

In [104]:
data2=([1,2,3,4],[5,6,7,8])
print(data2)
print(type(data2))
data2=np.array(data2)
print(data2)
print(data2.shape)
print(data2.ndim)


([1, 2, 3, 4], [5, 6, 7, 8])
<class 'tuple'>
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [105]:
array2 = np.array(data2)
array2.shape

(2, 4)

In [106]:
data2=([1,2,3,4],[5,6,7,8])
data2=np.array(data2)
data2.shape

(2, 4)

In [107]:
data2.ndim

2

In [108]:
data2.shape

(2, 4)

In [109]:
data2.dtype

dtype('int64')

In [39]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
np.ones(4)

array([1., 1., 1., 1.])

In [115]:
arr2=np.empty((2,2,2))
arr2

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [48]:
arr=np.empty((2,3,2))
arr

array([[[1.08333767e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.08221785e-311, 8.60952352e-072]],

       [[4.47206533e-090, 2.74954873e+180],
        [1.56150274e+184, 3.34502212e-061],
        [6.48224659e+170, 4.93432906e+257]]])

In [ ]:
arr2=np.empty((2,2,2))
arr2

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [59]:
import numpy as np
arr1=np.empty((5,3,2))
arr1

array([[[1.08329861e-311, 1.02765654e-321],
        [0.00000000e+000, 0.00000000e+000],
        [7.56571287e-307, 5.02034658e+175]],

       [[5.93624617e-038, 1.83086008e-076],
        [1.46397681e-047, 3.14189799e+179],
        [4.46595244e-062, 7.75835242e-144]],

       [[3.59751658e+252, 3.96046095e+246],
        [1.04918621e-153, 7.69165785e+218],
        [5.04621343e+180, 1.04917822e-153]],

       [[9.08366793e+223, 5.93624617e-038],
        [1.83086008e-076, 1.46397681e-047],
        [3.14189799e+179, 1.04914918e-153]],

       [[1.94918966e-153, 4.75387789e-038],
        [9.72389950e-067, 1.24555660e-047],
        [2.59027896e-144, 7.79952704e-143]]])

In [60]:
arr1=np.empty((1,2,3,2,3))
arr1

array([[[[[1.08331809e-311, 1.19069821e-321, 0.00000000e+000],
          [0.00000000e+000, 0.00000000e+000, 1.16097020e-028]],

         [[1.26138597e-076, 2.92683616e-028, 6.00166378e-067],
          [1.04917183e-153, 5.23081515e-143, 1.58736141e-076]],

         [[2.27236416e+184, 2.08793528e-076, 5.34850385e-038],
          [6.47826489e-144, 3.59751658e+252, 1.46901661e+179]]],


        [[[8.37404147e+242, 4.31999013e-096, 4.82337723e+228],
          [2.65124317e-032, 6.51712480e-038, 7.72821265e-091]],

         [[1.21496969e-046, 9.30263873e+165, 5.04621343e+180],
          [1.94918963e-153, 1.84745704e+184, 2.34091144e-057]],

         [[3.34944632e-061, 2.34303992e-056, 1.04914907e-153],
          [9.08366791e+223, 5.82381891e-144, 6.17582057e-322]]]]])

In [61]:
arr1.shape

(1, 2, 3, 2, 3)

In [120]:
import numpy as np
arr1 =np.array([[1,2,3],[4,5,6]])
print(arr1)
print('----')
arr2=np.array([[7,8,9],[10,11,12]])
print(arr2)
print('----')


[[1 2 3]
 [4 5 6]]
----
[[ 7  8  9]
 [10 11 12]]
----


In [122]:
arr1+arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [123]:
arr3=np.vstack((arr1,arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [124]:
#import numpy as np
arr3=np.hstack((arr1,arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [125]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [126]:
print(arr2)

[[ 7  8  9]
 [10 11 12]]


In [127]:
arr3=np.concatenate((arr1,arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [128]:
arr3 = np.concatenate([arr1, arr2],axis=0)
print(arr3)
print(arr3.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [129]:
arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)
